### ISSUE TITLE
[Question] Does the project durable?

### ISSUE THREAD

**Issue by ClSlaid** [PauMAVA/cargo-ramdisk#2]
Hello maintainer, I noticed your project from this [reply](https://github.com/feather-rs/feather/issues/531#issuecomment-1033644494).In your reply, you mentioned that your project may suffer from a loss of builds in shutdowns and reboots.
So I'd like to ask does the ramdisk write back to disk every time the build is finished? This may solve the durability problem.

**Comment by PauMAVA** [comment]
Hello @ClSlaid ! As for now, the ramdisk contents are not written back to the original target directory. Despite this, I had already in mind this feature and will probably implement it in the following days.

Thanks for your interest in the project!

**Comment by PauMAVA** [comment]
Hello @ClSlaid. I, unfortunately, had no time to implement this feature on my own but recently @psdzzm provided a PR that fixes this via the `--copy-back` option.

This is solved.
